<a href="https://colab.research.google.com/github/IamThePalak/Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy ---- Numerical Python
Advantages of NumPy Array
1. allow several mathematical operation
2. allow faster operation

In [29]:
import numpy as np

In [19]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

1 dimension numpy array

In [20]:
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

2 dimension NumPy array

In [21]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

Array of Particular value

In [22]:
c=np.full((4,3),5)
print(c)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


Create an identity matrix

In [23]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a numpy array with random values

In [24]:
b=np.random.random((2,3))
print(b)

[[0.64086254 0.43451777 0.27927345]
 [0.07643051 0.48763012 0.07503567]]


Create a numpy array with random integers

In [25]:
c=np.random.randint(20,30,(2,3))
print(c)

[[29 27 24]
 [25 23 20]]


Array of evenly spaced values ---- specify no.of values required

In [33]:
d=np.linspace(10,40,4)
print(d)

[10. 20. 30. 40.]


Array of evenly spaced values --- specify step required

In [32]:
 e = np.arange(10,40,4)
 print(e)

[10 14 18 22 26 30 34 38]


Analysing NumPy Array

In [35]:
d = np.random.randint(10,80,(4,5))
print(d)

[[40 24 48 24 31]
 [50 68 56 25 30]
 [11 38 58 78 37]
 [53 68 36 22 53]]


Array Dimension

In [37]:
print(d.shape)


(4, 5)


Number of Dimension

In [38]:
print(d.ndim)

2


Number of elements in an array

In [40]:
print(d.size)

20


Checking the datatype of values in the array

In [41]:
print(d.dtype)

int64


Mathematical operations on NumpyArray

In [42]:
list1=[1,3,4,5]
list2=[6,7,8,9]
print(list1+list2)

[1, 3, 4, 5, 6, 7, 8, 9]


In [44]:
a = np.random.randint(0,10,(3,3))
print(a)

[[0 1 2]
 [4 0 9]
 [8 9 9]]


In [45]:
b = np.random.randint(10,20,(3,3))
print(b)

[[15 13 15]
 [16 17 14]
 [10 10 10]]


In [46]:
print(a+b)

[[15 14 17]
 [20 17 23]
 [18 19 19]]


In [47]:
print(a-b)

[[-15 -12 -13]
 [-12 -17  -5]
 [ -2  -1  -1]]


In [48]:
print(a*b)

[[  0  13  30]
 [ 64   0 126]
 [ 80  90  90]]


In [49]:
print(a/b)

[[0.         0.07692308 0.13333333]
 [0.25       0.         0.64285714]
 [0.8        0.9        0.9       ]]


In [50]:
print(np.add(a,b))

[[15 14 17]
 [20 17 23]
 [18 19 19]]


Array Manipulation

In [51]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 8 6]
 [6 1 7]]
(2, 3)


Transpose of an array

In [52]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[8 6]
 [8 1]
 [6 7]]
(3, 2)


Reshape of an Array

In [53]:
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 6 2]
 [1 4 5]]
(2, 3)


In [54]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 6]
 [2 1]
 [4 5]]
(3, 2)
